### ISSUE TITLE
crash shortly after operations are complete

### ISSUE THREAD

**Issue by SilentSymphony** [rexxar-tc/GetOutOfMySandboxPlugin#1]
I've just tested the plugin out and the operation actually completes nicely reducing map size without issue until shortly after everything shuts down, Disabling it afterwards seems to stop the crash.

Server Log: http://puu.sh/m5zO3/32c44263f3.txt
Plugin Log: http://puu.sh/m5zQV/04b9d98634.txt

I don't really see much in the logs, I'll be reproducing the crash with fresh logs when i get a chance ASAP.

**Comment by SilentSymphony** [comment]
Seems to be resolved after switching to a new map.

**Comment by rexxar-tc** [comment]
Excellent. My guess is that Ken fixed it when they fixed whatever was causing concealment to be unstable.
